name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [stable, beta]

    steps:
    - uses: actions/checkout@v6
    - name: Modify the rust toolchain version
      run: rustup override set ${{ matrix.toolchain }}
    # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --release --all-targets
    - name: Run apps
      run: ./scripts/run-app.sh local-pbft | grep -E "Finished [1-9][0-9]{3,} rounds"